app:
  project: deploy-elibrary
  tier: application

image:
  repository: jedi132000/nextapp
  tag: latest

deployments: 
  containerName: application
  containerPort: 3000
  imagePullPolicy: Always
  replicas: 1

service:
  type: NodePort
  port: 3000         
  targetPort: 3000
  nodePort: 31111